### ISSUE TITLE
Mobile Comment Input 

### ISSUE THREAD

**Issue by Dotsung** [Dotsung/Dotia#6]
Issue tracker is ONLY used for reporting bugs. New features should be discussed on our slack channel. Please use stackoverflow for supporting issues.

## Expected Behavior

Comment input should be on the bottom.

## Current Behavior

Comment input is fucked.

## Possible Solution

hit @haya0206 .

## Steps to Reproduce

1. 
2.
3.
4.

**Comment by haya0206** [comment]
Fuck you
